### ISSUE TITLE
Validation warnings on Maven 3.9+

### ISSUE THREAD

**Issue by AB-xdev** [floverfelt/find-and-replace-maven-plugin#10]
When running the plugin on Maven 3.9+ the following warnings are printed out:

``-Dmaven.plugin.validation=VERBOSE``
```
[WARNING]  * io.github.floverfelt:find-and-replace-maven-plugin:1.1.0
...
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]    * Plugin mixes multiple Maven versions: [3.8.1, 2.2.1]
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-plugin-api:3.8.1, org.apache.maven:maven-artifact:3.8.1, org.apache.maven:maven-model:3.8.1]
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
```

**Comment by hazendaz** [comment]
#8 was same.

@AB-xdev Are you planning to just take over as nothing happening here? I see you got rid of the other issue that popped today that I'm going to open a ticket here . Maven dropped commons-lang3 from maven 3.9.8 so yet another new thing breaking.  I'll switch over to your fork if its considered long term rather than something temporary.
